"""add phase2 tables: price_cache, snapshots, allocation_targets

Revision ID: 9ab4e0ff5b84
Revises: bb5a0b9889a1
Create Date: 2026-03-23 23:50:31.727554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab4e0ff5b84'
down_revision: Union[str, None] = 'bb5a0b9889a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('target_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('latest_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_profit_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('holdings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('price_cache')
    op.drop_table('allocation_targets')
    # ### end Alembic commands ###
